### ISSUE TITLE
[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by xzy103** [okcoin-okex/API-docs-OKEx.com#152]
已使用科学上网，为何还是这样？Python3.7
![](https://github.com/xzy103/Picture-L/blob/master/001.PNG?raw=true)
以下是相关代码↓↓
![](https://github.com/xzy103/Picture-L/blob/master/002.PNG?raw=true)
![](https://github.com/xzy103/Picture-L/blob/master/003.PNG?raw=true)

**Comment by aaron317** [comment]
你ping一下real.okex.com        你需要买个国外的服务器  或者香港阿里云服务器

**Comment by bayhax** [comment]
把梯子设置为全局代理
