### ISSUE TITLE
提币withdraw接口只支持BTC/ETH等5个币种吗？如果支持其他币种手续费chargefee如何设置？

### ISSUE THREAD

**Issue by wlchn** [okcoin-okex/API-docs-OKEx.com#169]
提币withdraw接口只支持BTC/ETH等5个币种吗？如果支持其他币种那手续费chargefee如何设置？

**Comment by wlchn** [comment]
@aaron317 能否增加一个查询chargefee的API或者文件，如果除了在web一个一个看没有可查源，那么应该可以省略这个参数，不传默认和web一致。

**Comment by aaron317** [comment]
v3  api是可以的  。还没有上线。正在内测当中

**Comment by aaron317** [comment]
好的，我提交了这个意见， 应该会增加这个接口的，感谢你的反馈哈

Alan Wang <notifications@github.com> 于2018年9月26日周三 下午10:44写道：

**Comment by westerpants** [comment]
> v3 api是可以的 。还没有上线。正在内测当中

預計v3 api 大概甚麼時候上綫?

**Comment by celon** [comment]
> > > v3 api是可以的。还没有上线。正在内测当中
> > 
> > 
> > 预计v3 api大概什么时候上线？
> 
> 已经上线了

请问 v3 对应的文档在哪里？
