### ISSUE TITLE
连接WebSocket一直显示超时，也确认终端翻墙了

### ISSUE THREAD

**Issue by DreamXzxy** [okcoin-okex/API-docs-OKEx.com#170]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 69.171.244.15:10441
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

**Comment by DreamXzxy** [comment]
刚试了下wss://real.okex.com:10441/websocket这个地址也不行

**Comment by catalsdevelop** [comment]
你可以参考下ccxt这个分支上的实现，我之前测试okex的ws接口，是可以用的
https://github.com/lfern/ccxt/blob/feature/websockets-multiple/js/okex.js

**Comment by DreamXzxy** [comment]
> 你可以参考下ccxt这个分支上的实现，我之前测试okex的ws接口，是可以用的
> https://github.com/lfern/ccxt/blob/feature/websockets-multiple/js/okex.js

他用的地址和我用的是一样的，都是wss://real.okex.com:10441/websocket，在终端跑不起来，浏览器测试都可以正常返回数据

**Comment by catalsdevelop** [comment]
我试了下基本的流程，是可以返回数据的，下面是参考代码。我猜你的翻墙有问题，你可以试一下全局socket5代理。

```js
const WebSocket = require('ws')

const ws = new WebSocket('wss://real.okex.com:10441/websocket')

ws.on('open', function open() {
  ws.send('{"event":"addChannel","channel":"ok_sub_spot_bch_btc_ticker"}')
})

ws.on('message', function incoming(data) {
  console.log(data)
})
```

**Comment by DreamXzxy** [comment]
> 我试了下基本的流程，是可以返回数据的，下面是参考代码。我猜你的翻墙有问题，你可以试一下全局socket5代理。

em...你的代码还是一样的错误，那可能真的是我终端翻墙有问题，问题是我终端输入 curl ip.cn 返回的也确实是我代理的地址，跑币安交易所的代码也是好好的也没被墙。

**Comment by arpitec** [comment]
Hi，你

> > 我试了下基本的流程，是可以返回数据的，下面是参考代码。我猜你的翻墙有问题，你可以试一下全局socket5代理。
> 
> em...你的代码还是一样的错误，那可能真的是我终端翻墙有问题，问题是我终端输入 curl ip.cn 返回的也确实是我代理的地址，跑币安交易所的代码也是好好的也没被墙。

Hi，你在墙内跑币安得wss没有问题么？是用的什么样的代理环境？我跑币安会出现和你一样的问题，但是跑火币的wss却又没问题。
