### ISSUE TITLE
websocket 503 Service Temporarily Unavailable错误是咋回事？

### ISSUE THREAD

**Issue by Henry8023** [okcoin-okex/API-docs-OKEx.com#187]
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by OkTechnicalSupport** [comment]
请您在请求一下现在还是否出现这个问题。
