### ISSUE TITLE
api v3 : User does not exist, when get info from futures api ?

### ISSUE THREAD

**Issue by githubcyc** [okcoin-okex/API-docs-OKEx.com#196]
full url is:  https://www.okex.com/api/futures/v3/accounts

I put the right apiKey, secretKey, psw, but result is `{"code":32038,"message":"User does not exist"}`,
it's **incrediable** 😲  !!!
then i change apiKey to an error key, the result is `{"code":30006,"message":"Invalid OK-ACCESS-KEY"}`
I wonder what does the `User does not exist` mean ???  THX for everyone !😄 
```
ok = Okex(key, secret, psw)
result = ok.get_accounts()
```

**Comment by OkTechnicalSupport** [comment]
Hello, sir. Please request your interface according to our documents.

**Comment by linmaosong2018** [comment]
@githubcyc have you found a solution? I am having the same issue and I wonder if it's something to do with sub account.

**Comment by linmaosong2018** [comment]
Update: this error appears to happen when the API key is used before the pre-trade Quiz is done.

For me, this was the fixed after - 
* log into the trading screen, which brings up the (one off) trading quiz
* pass the quiz
* click 'agree' on the next screen of terms and conditions

**Comment by OkTechnicalSupport** [comment]
Are you a logged-in OKEX station? You need the corresponding APIkey to pass parameters. Please operate according to the document.

**Comment by githubcyc** [comment]
@OkTechnicalSupport It seems that the prompt `User does not exist` is error,  as just the user doesn't pass pre-trade Quiz in trading screen.
