### ISSUE TITLE
能不能用点心？

### ISSUE THREAD

**Issue by liurenqiu520** [okcoin-okex/API-docs-OKEx.com#200]
官网的接口都经历过V2,V3了，这咋还是V1的旧文档？

**Comment by OkTechnicalSupport** [comment]
这是V1的文档，V3目前在git还没有文档 ，您需要可以给您发一份V3的文档和官网的SDK     https://www.okex.com/docs/zh/#spot_leverage-query  V3文档     https://github.com/okcoin-okex/open-api-v3-sdk  V3SDK
