### ISSUE TITLE
rest api v3/orders get response { code: 30012, message: 'Invalid Authority' }

### ISSUE THREAD

**Issue by lcinvault** [okcoin-okex/API-docs-OKEx.com#203]
what's the meaning of invalid authority? Is my api key can not post an order? or my request sign is not right? So how can I get a right right response?

**Comment by CanKattwinkel** [comment]
@lcinvault how did you end up solving the error?

**Comment by TrangJun** [comment]
Hi, I alse have this issus. Can you help me to fix this?

**Comment by scottyinthematrix** [comment]
@lcinvault I'm having the same issue, why is it closed, did you find the root cause, could you share it?

**Comment by ethanbrown3** [comment]
I'm having this issue now as well. Not finding much help.
