### ISSUE TITLE
OKEx websocket api here 

### ISSUE THREAD

**Issue by qyvlik** [okcoin-okex/API-docs-OKEx.com#3]
https://support.okcoin.com/hc/zh-cn/articles/360000754131

**Comment by MadaoBuf** [comment]
future ticker is ok?
 I can't  receive any response information by websocket in future ticker's API.

**Comment by qyvlik** [comment]
@MadaoBuf look here https://support.okcoin.com/hc/zh-cn/articles/360000758331-WebSocket-API%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98, your can contact the employees of the okex.com

**Comment by peterzhangbo** [comment]
@qyvlik @MadaoBuf https://github.com/okcoin-okex/API-docs-OKEx.com    More docs here.
