### ISSUE TITLE
合约接口

### ISSUE THREAD

**Issue by lubing7683** [okcoin-okex/API-docs-OKEx.com#6]
websocket合约接口没有吗?

**Comment by ghostli123** [comment]
You may replace "spot" with "future" in this document, https://support.okcoin.com/hc/zh-cn/articles/360000754131

**Comment by peterzhangbo** [comment]
@lubing7683 @ghostli123 https://github.com/okcoin-okex/API-docs-OKEx.com/tree/master/API-For-Futures-CN      这里
